version: '3.6'
services:
  proxy-apache2:
    image: bitnami/apache
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./app-client/dist/app-client:/app
      - ./httpd.conf:/bitnami/apache/conf/vhosts/my_vhost.conf:ro
    